_target_: src.models.unet_module.UNETLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.network_unet.UNet
  in_nc: 1
  out_nc: 1
  nc: [64, 128, 256, 512]
  nb: 2
  act_mode: 'R'
  downsample_mode: 'strideconv'
  upsample_mode: 'convtranspose'

# compile model for faster training with pytorch 2.0
compile: false